apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}-config
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  config.yaml: |
    json_logs: {{ index .Values.config "json_logs" }}
    log_config:
      level: {{ index .Values.config.log_config "level" | default "info" | quote }}
      format: {{ index .Values.config.log_config "format" | default "json" | quote }}
      add_source: {{ index .Values.config.log_config "add_source" | default false }}
    tile_colors:
      {{- range (index .Values.config "tile_colors") }}
      - {{ . | quote }}
      {{- end }}

